apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m04mc4y7s-go 
  janus-idp.io/tekton: m04mc4y7s-go
  backstage.io/kubernetes-id: m04mc4y7s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m04mc4y7s-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml