apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m04mc4y7s-go
  janus-idp.io/tekton: m04mc4y7s-go
  backstage.io/kubernetes-id: m04mc4y7s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m04mc4y7s-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
